04_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create', views.create, name='create'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

04_pjt/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    release_date = models.DateField()
    genre = models.CharField(max_length=30)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()
    

04_pjt/movies/views.py
from django.shortcuts import render, redirect

from movies.models import Movie

# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie' : movie,
    }
    return render(request, 'movies/index.html', context)

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie' : movie,
    }
    return render(request, 'movies/detail.html', context)

def new(request):
    return render(request, 'movies/new.html')

def create(request):
    title = request.POST.get('title')
    audience = request.POST.get('audience')
    release_date = request.POST.get('release_date')
    genre = request.POST.get('genre')
    score = request.POST.get('score')
    poster_url = request.POST.get('poster_url')
    description = request.POST.get('description')

    movie = Movie(title=title, audience=audience, release_date=release_date, genre=genre, score=score, poster_url=poster_url, description=description)
    movie.save()
    return redirect('movies:detail', movie.pk)

def edit(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie' : movie,
    }
    return render(request, 'movies/edit.html', context)

def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()

    return redirect('movies:index')

def update(request, pk):
    movie = Movie.objects.get(pk=pk)

    movie.title = request.POST.get('title')
    movie.audience = request.POST.get('audience')
    movie.release_date = request.POST.get('release_date')
    movie.genre = request.POST.get('genre')
    movie.score = request.POST.get('score')
    movie.poster_url = request.POST.get('poster_url')
    movie.description = request.POST.get('description')

    movie.save()

    return redirect('movies:detail', movie.pk)

04_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container row p-3">
    <div class="col-6">     
      <img width="100%" src="{{ movie.poster_url }}">   
    </div>
    <div class="col-6">
      <p class="pt-3 fs-1 fw-semibold">{{ movie.title }}</p>
      <p>Audience : {{ movie.audience }}</p>
      <p>Release Dates: {{ movie.release_date }}</p>
      <p>Genre : {{ movie.genre }}</p>
      <p>Score : {{ movie.score }}</p>
      <p>Description : {{ movie.description|truncatechars:150 }}</p>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <a class="btn btn-outline-success" href="{% url 'movies:edit' movie.pk %}">EDIT</a>
    <div style="width:10px;">
    </div>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST">
        {% csrf_token %}
        <input class="btn btn-outline-danger" type="submit" value = "DELETE">
    </form>
  </div>
  <hr>
  <div class="text-center">
    <a class="btn btn-light" href="{% url 'movies:index' %}">BACK</a>
  </div>
{% endblock content %}

04_pjt/movies/templates/movies/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="fw-semibold">EDIT</h1>
  <hr>
  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title">TITLE</label>
        <input class="form-control" type="text" id="title" name="title" value="{{ movie.title }}">
    </div>
    <div class="mb-3">
        <label for="audience">AUDIENCE</label>
        <input class="form-control" type="text" id="audience" name="audience" value="{{ movie.audience }}">
    </div>
    <div class="mb-3">
        <label for="release_date">RELEASE_DATE</label>
        <input class="form-control" type="date" name="release_date" value="{{ movie.release_date|date:'Y-m-d' }}">
    </div>
    <div class="mb-3">
        <label for="genre">GENRE</label>
        <select class="form-control" name="genre" id="genre" value="{{ movie.genre }}">
            <option value="선택">--선택--</option>
            <option value="액션" {% if movie.genre == "액션" %} selected {% endif%} >액션</option>
            <option value="범죄" {% if movie.genre == "범죄" %} selected {% endif%} >범죄</option>
            <option value="코미디" {% if movie.genre == "코미디" %} selected {% endif%} >코미디</option>
            <option value="로맨스" {% if movie.genre == "로맨스" %} selected {% endif%} >로맨스</option>
            <option value="스릴러" {% if movie.genre == "스릴러" %} selected {% endif%} >스릴러</option>
            <option value="공포" {% if movie.genre == "공포" %} selected {% endif%} >공포</option>
            <option value="멜로" {% if movie.genre == "멜로" %} selected {% endif%} >멜로</option>
            <option value="뮤지컬" {% if movie.genre == "뮤지컬" %} selected {% endif%} >뮤지컬</option>
            <option value="음악" {% if movie.genre == "음악" %} selected {% endif%} >음악</option>
            <option value="기타" {% if movie.genre == "기타" %} selected {% endif%} >기타</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="score">SCORE</label>
        <input class="form-control" type="text" name="score" name="score" value="{{ movie.score }}">
    </div>
    <div class="mb-3">
        <label for="poster_url">POSTER_URL</label>
        <input class="form-control" type="text" id="poster_url" name="poster_url" value="{{ movie.poster_url }}">
    </div>
    <div class="mb-3">
        <label for="description">DESCRIPTION</label>
        <textarea class="form-control" name="description" id="description" cols="30" rows="5">{{ movie.description }}</textarea>
    </div>
    <input class="btn btn-outline-success" type="reset" value="Reset">
    <input class="btn btn-outline-danger" type="submit" value="Submit">
  </form>
  <hr>
  <a class="btn btn-outline-primary btn-sm"  href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}

04_pjt/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="text-center">
    <h1 class="font-monospace fw-bold fs-1" style="color:#d63384">Movie World</h1>
    <div style="width:100%; display:flex; justify-content:row-reverse">
      <a class="btn btn-outline-secondary btn-sm" href="{% url 'movies:new' %}">+</a>
    </div>   
    <hr>
    <div class="container row">
      {% for movie in movie %}
      <div class="col-4">
        <img class="m-2" width="100%" src="{{ movie.poster_url }}"><br>
        <a class="fw-semibold fs-5 text-decoration-none text-black" href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a>
        <p>💕{{ movie.score }}</p>
        <hr>
      </div>
      {% endfor %} 
    </div> 
  </div>
{% endblock content %}

04_pjt/movies/templates/movies/new.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="fw-semibold">NEW</h1>
  <hr>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title">TITLE</label>
        <input class="form-control" type="text" id="title" name="title">
    </div>
    <div class="mb-3">
        <label for="audience">AUDIENCE</label>
        <input class="form-control" type="text" id="audience" name="audience">
    </div>
    <div class="mb-3">
        <label for="release_date">RELEASE_DATE</label>
        <input class="form-control" type="date" name="release_date">
    </div>
    <div class="mb-3">
        <label for="genre">GENRE</label>
        <select class="form-control" name="genre" id="{{ movie.genre }}">
            <option value="선택">--선택--</option>
            <option value="액션">액션</option>
            <option value="범죄">범죄</option>
            <option value="코미디">코미디</option>
            <option value="로맨스">로맨스</option>
            <option value="스릴러">스릴러</option>
            <option value="공포">공포</option>
            <option value="멜로">멜로</option>
            <option value="뮤지컬">뮤지컬</option>
            <option value="음악">음악</option>
            <option value="기타">기타</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="score">SCORE</label>
        <input class="form-control" type="text" name="score" name="score">
    </div>
    <div class="mb-3">
        <label for="poster_url">POSTER_URL</label>
        <input class="form-control" type="text" id="poster_url" name="poster_url">
    </div>
    <div class="mb-3">
        <label for="description">DESCRIPTION</label>
        <textarea class="form-control" name="description" id="description" cols="30" rows="5"></textarea>
    </div>
    <input class="btn btn-dark mt-2 btn-sm" type="submit" value="submit">
  </form>
  <hr>
  <a class="btn btn-outline-primary btn-sm" href="{% url 'movies:index' %}">BACK</a>

{% endblock content %}